
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
export const Index = {
  "default": {
    "AnimatedSubscribeButtonDemo": {
      name: "AnimatedSubscribeButtonDemo",
      type: "components:example",
      registryDependencies: ["animated-subscribe-button"],
      component: () => import("../src/lib/registry/default/example/AnimatedSubscribeButtonDemo.vue").then((m) => m.default),
      files: ["../src/lib/registry/default/example/AnimatedSubscribeButtonDemo.vue"],
    },
    "BentoDemo": {
      name: "BentoDemo",
      type: "components:example",
      registryDependencies: ["bento-grid"],
      component: () => import("../src/lib/registry/default/example/BentoDemo.vue").then((m) => m.default),
      files: ["../src/lib/registry/default/example/BentoDemo.vue"],
    },
    "HeroVideoDialogDemo": {
      name: "HeroVideoDialogDemo",
      type: "components:example",
      registryDependencies: ["hero-video-dialog"],
      component: () => import("../src/lib/registry/default/example/HeroVideoDialogDemo.vue").then((m) => m.default),
      files: ["../src/lib/registry/default/example/HeroVideoDialogDemo.vue"],
    },
    "KbdDemo": {
      name: "KbdDemo",
      type: "components:example",
      registryDependencies: ["kbd"],
      component: () => import("../src/lib/registry/default/example/KbdDemo.vue").then((m) => m.default),
      files: ["../src/lib/registry/default/example/KbdDemo.vue"],
    },
    "Marquee3DDemo": {
      name: "Marquee3DDemo",
      type: "components:example",
      registryDependencies: ["marquee"],
      component: () => import("../src/lib/registry/default/example/Marquee3DDemo.vue").then((m) => m.default),
      files: ["../src/lib/registry/default/example/Marquee3DDemo.vue"],
    },
    "MarqueeDemo": {
      name: "MarqueeDemo",
      type: "components:example",
      registryDependencies: ["marquee"],
      component: () => import("../src/lib/registry/default/example/MarqueeDemo.vue").then((m) => m.default),
      files: ["../src/lib/registry/default/example/MarqueeDemo.vue"],
    },
    "MarqueeVerticalDemo": {
      name: "MarqueeVerticalDemo",
      type: "components:example",
      registryDependencies: [],
      component: () => import("../src/lib/registry/default/example/MarqueeVerticalDemo.vue").then((m) => m.default),
      files: ["../src/lib/registry/default/example/MarqueeVerticalDemo.vue"],
    },
    "PhoneInputDefaultDemo": {
      name: "PhoneInputDefaultDemo",
      type: "components:example",
      registryDependencies: ["phone-input"],
      component: () => import("../src/lib/registry/default/example/PhoneInputDefaultDemo.vue").then((m) => m.default),
      files: ["../src/lib/registry/default/example/PhoneInputDefaultDemo.vue"],
    },
    "PhoneInputDemo": {
      name: "PhoneInputDemo",
      type: "components:example",
      registryDependencies: ["phone-input"],
      component: () => import("../src/lib/registry/default/example/PhoneInputDemo.vue").then((m) => m.default),
      files: ["../src/lib/registry/default/example/PhoneInputDemo.vue"],
    },
    "PhoneInputFormDemo": {
      name: "PhoneInputFormDemo",
      type: "components:example",
      registryDependencies: ["button","form","phone-input"],
      component: () => import("../src/lib/registry/default/example/PhoneInputFormDemo.vue").then((m) => m.default),
      files: ["../src/lib/registry/default/example/PhoneInputFormDemo.vue"],
    },
    "PhoneInputIntDemo": {
      name: "PhoneInputIntDemo",
      type: "components:example",
      registryDependencies: ["phone-input"],
      component: () => import("../src/lib/registry/default/example/PhoneInputIntDemo.vue").then((m) => m.default),
      files: ["../src/lib/registry/default/example/PhoneInputIntDemo.vue"],
    },
    "ReviewCard": {
      name: "ReviewCard",
      type: "components:example",
      registryDependencies: ["utils"],
      component: () => import("../src/lib/registry/default/example/ReviewCard.vue").then((m) => m.default),
      files: ["../src/lib/registry/default/example/ReviewCard.vue"],
    },
  },
}
